# Numpy,Pandas,Scipy를 활용한 통계학 기반 데이터 분석 가이드

##### Author: JHan

-----

In [8]:
# package import
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
%matplotlib inline

* Numpy
-----

In [60]:
arr1 = np.arange(0, 100)
# arr1 = array([1,2,3....98,99])
arr2 = np.linspace(0, 2*np.pi, 100)
arr2 = np.sin(arr2)
arr3 = arr1[::-1] # arr1의 역순 배열 생성
# 예시를 위한 array1 및 arr2 (0~2pi sin함수) 생성

In [59]:
arr3

array([], dtype=int64)

In [50]:
np.mean(arr1) # out: np.float64(50.)
np.var(arr1) # out: np.float(833.25)
np.std(arr1) # out: np.float(28.866)
np.sqrt(np.var(arr1)) # out: np.float(28,866)

기본적인 함수로서 np.mean은 평균, np.var는 분산(데이터가 평균으로부터 얼마나 퍼져있는지를 나타내는 척도)
np.std는 표준편차 (분산의 제곱근 // np.std == np.sqrt(np.var))

In [55]:
#np.median(arr1) == np.percentile(arr1, 50)

#np.median은 중앙값을 반환해주며
#np.percentile(array, q)는 q 백분위에 해당되는 값을 계산해서 반환해줌

np.min(arr1)
np.max(arr1)
np.ptp(arr1) # == np.max - np.min, peak to peak

np.int64(99)

In [72]:
np.cov(arr1, arr3)

array([[ 841.66666667, -841.66666667],
       [-841.66666667,  841.66666667]])


![cov](../../cov.png)

np.cov를 통해 얻어지는 array의 의미는 사진과 같음
공분산이 양수면 양의 선형관계, 음수면 음의 선형관계를 가진다는 의미

In [74]:
np.corrcoef(arr1, arr3)

array([[ 1., -1.],
       [-1.,  1.]])

np.corrcoef는 피어슨 상관계수 행렬을 이용하여 두 변수 간 선형 상관도를 측정함.
arr3 변수는 arr1변수의 역순 행렬이므로 -1인 강한 음의 상관관계를 가지며 이를 correcoef로 판별할수있음

In [104]:
np.ndarray((2,3,4), dtype='int8')

#np. ndarray를 이용하여 다차원 행렬을 생성할수 있음.

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [106]:
arr1[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* numpy array에 대한 연산을 시행할경우 루프문 없이도 각 vector에 자동적으로 연산을 수행함

In [109]:
arr1[0:10] * 1.1

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

In [115]:
arr4 = np.array([0,0,-1,0,0,0,1,0], dtype='int8')

In [118]:
arr4.argmax()
# array내 가장 큰 vector의 index값을 반환해줌, 제일 작은 값은 argmin을 사용

np.int64(6)